elasticsearch_master:
    image: elasticsearch:2.3.3
    command: "elasticsearch -Des.cluster.name=elasticsearch -Des.node.master=true"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /Users/isaac/work/data:/usr/share/elasticsearch/data
    user: "1000"

elasticsearch1:
    image: elasticsearch:2.3.3
    command: "elasticsearch -Des.cluster.name=elasticsearch -Des.discovery.zen.ping.unicast.hosts=elasticsearch_master"
    links:
      - elasticsearch_master
    volumes:
      - /Users/isaac/work/data:/usr/share/elasticsearch/data
    user: "1000"
